/**
 * Generates lib/tech-icons.ts from simple-icons + devicon.
 *
 * Monochrome only: fills are stripped so paths inherit `currentColor`.
 * simple-icons is the default source (uniform 24x24, single path, optically
 * consistent). devicon covers the brands simple-icons dropped for trademark
 * reasons (Amazon, Microsoft, LinkedIn).
 *
 * Run: node scripts/generate-icons.mjs
 */
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import * as simpleIcons from "simple-icons";

// key -> simple-icons export name
const FROM_SIMPLE = {
  python: "siPython",
  cpp: "siCplusplus",
  c: "siC",
  java: "siOpenjdk",
  typescript: "siTypescript",
  javascript: "siJavascript",
  react: "siReact",
  nextjs: "siNextdotjs",
  node: "siNodedotjs",
  dotnet: "siDotnet",
  django: "siDjango",
  flask: "siFlask",
  mongodb: "siMongodb",
  postgresql: "siPostgresql",
  mysql: "siMysql",
  docker: "siDocker",
  podman: "siPodman",
  kubernetes: "siKubernetes",
  linux: "siLinux",
  git: "siGit",
  github: "siGithub",
  githubactions: "siGithubactions",
  pandas: "siPandas",
  numpy: "siNumpy",
  pytorch: "siPytorch",
  scikitlearn: "siScikitlearn",
  opencv: "siOpencv",
  jupyter: "siJupyter",
  tailwind: "siTailwindcss",
  prisma: "siPrisma",
  firebase: "siFirebase",
  webgl: "siWebgl",
  graphql: "siGraphql",
  redis: "siRedis",
  vercel: "siVercel",
  arduino: "siArduino",
  raspberrypi: "siRaspberrypi",
  spark: "siApachespark",
  sqlite: "siSqlite",
  html: "siHtml5",
  css: "siCss",
};

// key -> devicon svg path (brands simple-icons no longer carries)
const FROM_DEVICON = {
  aws: "amazonwebservices/amazonwebservices-plain-wordmark.svg",
  azure: "azure/azure-plain.svg",
  linkedin: "linkedin/linkedin-plain.svg",
};

// Display labels. Anything not listed falls back to the source's own title.
const LABELS = {
  cpp: "C++",
  aws: "AWS",
  azure: "Azure",
  linkedin: "LinkedIn",
  node: "Node.js",
  nextjs: "Next.js",
  postgresql: "PostgreSQL",
  scikitlearn: "scikit-learn",
  tailwind: "Tailwind",
  java: "Java",
  githubactions: "GitHub Actions",
  spark: "Apache Spark",
  raspberrypi: "Raspberry Pi",
};

const icons = {};

for (const [key, exportName] of Object.entries(FROM_SIMPLE)) {
  const icon = simpleIcons[exportName];
  if (!icon) throw new Error(`simple-icons is missing ${exportName} (key: ${key})`);
  icons[key] = {
    title: LABELS[key] ?? icon.title,
    viewBox: "0 0 24 24",
    paths: [icon.path],
  };
}

for (const [key, file] of Object.entries(FROM_DEVICON)) {
  const svg = readFileSync(`node_modules/devicon/icons/${file}`, "utf8");

  const viewBox = svg.match(/viewBox="([^"]+)"/)?.[1];
  if (!viewBox) throw new Error(`No viewBox in ${file}`);

  // Grab every path's `d`. devicon splits some marks across several paths.
  const paths = [...svg.matchAll(/<path\b[^>]*\bd="([^"]+)"/g)].map((m) => m[1]);
  if (paths.length === 0) throw new Error(`No <path> found in ${file}`);

  icons[key] = { title: LABELS[key] ?? key, viewBox, paths };
}

const banner = `// GENERATED by scripts/generate-icons.mjs — do not edit by hand.
// Sources: simple-icons (CC0), devicon (MIT). Fills stripped for monochrome.
`;

const body = `${banner}
export type TechIcon = {
  title: string;
  viewBox: string;
  paths: string[];
};

export const TECH_ICONS = ${JSON.stringify(icons, null, 2)} as const satisfies Record<string, TechIcon>;

export type TechKey = keyof typeof TECH_ICONS;
`;

mkdirSync("lib", { recursive: true });
writeFileSync("lib/tech-icons.ts", body);

const multi = Object.entries(icons).filter(([, v]) => v.paths.length > 1);
console.log(`Wrote lib/tech-icons.ts — ${Object.keys(icons).length} icons`);
console.log(`  simple-icons: ${Object.keys(FROM_SIMPLE).length}, devicon: ${Object.keys(FROM_DEVICON).length}`);
if (multi.length) {
  console.log(`  multi-path: ${multi.map(([k, v]) => `${k}(${v.paths.length})`).join(", ")}`);
}
